apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: monitoring

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-k8s
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: monitoring
