- job_name: 'weave'
  kubernetes_sd_configs:
  - api_server:
    role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace,__meta_kubernetes_pod_label_name]
    action: keep
    regex: ^kube-system;weave-net$
  - source_labels: [__meta_kubernetes_pod_container_name,__address__]
    action: replace
    target_label: __address__
    regex: ^weave;(.+?)(?::\d+)?$
    replacement: $1:6782
  - source_labels: [__meta_kubernetes_pod_container_name,__address__]
    action: replace
    target_label: __address__
    regex: ^weave-npc;(.+?)(?::\d+)?$
    replacement: $1:6781
  - source_labels: [__meta_kubernetes_pod_container_name]
    action: replace
    target_label: job
- job_name: 'elasticsearch_exporter'
  static_configs:
  - targets: ["elasticsearch.service.svc.cluster.local:9114"]
- job_name: 'redis_exporter'
  static_configs:
  - targets: ["redis.vocal.svc.cluster.local:9121"]
- job_name: 'couchdb_exporter'
  static_configs:
  - targets: ["couchdb.service.svc.cluster.local:9984"]
- job_name: 'postgresql_exporter'
  static_configs:
  - targets: ["postgresql.data.svc.cluster.local:9187"]
- job_name: 'rabbitmq_exporter'
  static_configs:
  - targets: ['rabbitmq.service.svc.cluster.local:9419']
- job_name: 'ldap_exporter'
  scrape_interval: 10s
  static_configs:
  - targets: ['ldap.data.svc.cluster.local:9142']
- job_name: 'calico_exporter'
  static_configs:
  - targets: ['calico-typha.kube-system.svc.cluster.local:9093']
- job_name: 'freeswitch_exporter'
  static_configs:
  - targets: ['10.132.0.9:9100']
- job_name: 'ingress-nginx_exporter'
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - ingress-nginx
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
    action: replace
    target_label: __scheme__
    regex: (https?)
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    target_label: __address__
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
  - source_labels: [__meta_kubernetes_service_name]
    regex: prometheus-adapter
    action: drop



    



