apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: ci-cd
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: ci-cd
      port: web
  baseImage: quay.io/prometheus/prometheus
  #  nodeSelector:
  #    beta.kubernetes.io/os: linux
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  additionalScrapeConfigs:
    name: additional-scrape-configs2
    key: prometheus-additional2.yaml
  version: v2.11.0
